### ISSUE TITLE
Project folder structure

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/unicornpkg-main#3]
With an project structure like in [xmake-repo](https://github.com/xmake-io/xmake-repo/tree/master/packages) finding a package will be easier.
Also there are some things in [xmake-repo abseil](https://github.com/xmake-io/xmake-repo/blob/master/packages/a/abseil/xmake.lua#L38) that unicornpkg cud yoink

**Comment by tomodachi94** [comment]
This is a good idea, but it might be overkill for this project's beginning stages. See: essays on premature optimization.

On a slightly different note, maybe we should prefix libraries with `lib***` as is the custom in dpkg...

**Comment by tomodachi94** [comment]
I feel that this is unnecessary. At most, there will be close to 70 packages, ever. Thank you for your time.
