### ISSUE TITLE
GitHub issue/PR templates

### ISSUE THREAD

**Issue by Commandcracker** [unicornpkg/unicornpkg-main#5]
issue Templates would be nice.
Templates that would accelerate development:

- Pakage Request
- Bug
- ...

A Pull Request template would also be neat

**Comment by tomodachi94** [comment]
I'm currently working on org-wide issue/PR templates, along with contributing guidelines and a code of conduct.

**Comment by tomodachi94** [comment]
Org-wide issue templates are now active. I'll tackle the PR template when I finish the contributing guidelines.
